### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by repo-do** [drivly/kafka.do#1]
```[tasklist]
### Tasks
- [x] Set up and configure the project to use wrangler as the development tool for Cloudflare Workers with Durable Objects.
- [x] Use wrangler to run, debug, and deploy the API according to the defined endpoints and applications lifecycle.
- [x] Apply middleware for authentication and formatting the requests and responses.
- [x] Set up Upstash connection
- [x] Lock down API to admins and workers
- [x] List all queues
- [x] Produce a message
- [x] Publish npm package
- [ ] Make npm package public
- [ ] https://github.com/drivly/kafka.do/issues/2
```
